version: '3'
services:
  customer:
    image: localhost/customer
    ports:
      - "4000:3000"
    networks:
      - westfield_mall
  burgerqueen:
    image: localhost/burgerqueen
    networks:
      - westfield_mall
  hobos:
    image: localhost/hobos
    networks:
      - westfield_mall
  iowafried:
    image: localhost/iowafried
    networks:
      - westfield_mall
networks:
  westfield_mall:
