apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
  labels:
    app: collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: aslaen/collector
          env:
          - name: COLLECTOR_PORT
            value: "4002"
          - name: COLLECTOR_DELEGATE_HOSTNAME
            value: "redis"
          - name: COLLECTOR_DELEGATE_PORT
            value: "80"
          ports:
          - containerPort: 4002
