apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  selector:
    app: customer
  ports:
    -
      protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort